id: applicationRequests
name: Accept Applicants by Age
description: Testing the ForEach state
version: '1.0'
start: AcceptState
functions:
- name: acceptStateFunction
  operation: https://192.168.1.204:31001/api/v1/namespaces/_/actions/hello?blocking=true&result=true
- name: acceptStateFunction2
  operation: https://192.168.1.204:31001/api/v1/namespaces/_/actions/hello2?blocking=true&result=true
states:
- name: AcceptState
  type: foreach
  inputCollection: "${ [.applicants[] | select(.age >= 18)] }"
  iterationParam: acceptedApplicant
  outputCollection: "${ .confirmationresults }"
  actions:
  - functionRef:
      refName: acceptStateFunction
      arguments:
        name: "${ .acceptedApplicant.name }"
        age: "${ .acceptedApplicant.age }"
  - functionRef:
      refName: acceptStateFunction2
      arguments: 
        payload: "${ .acceptedApplicant.zip }"
  - functionRef:
      refName: acceptStateFunction2
      arguments:
        payload: "${ .acceptedApplicant.address }"
  end: true
