id: applicantrequest
version: '1.0'
name: Applicant Request Decision Workflow
description: Determine if applicant request is valid
start: CheckApplication
functions:
  - name: startApplicationFunction
    operation: http://myorderservice.org/start
  - name: startApplicationFunction2
    operation: http://myorderservice.org/start2
  - name: sendRejectionEmailFunction
    operation: http://myorderservice.org/reject
states:
  - name: CheckApplication
    type: switch
    dataConditions:
      - condition: ".applicant | .age >= 18"
        transition: StartApplication
      - condition: ".applicant | .age < 18"
        transition: RejectApplication
    default:
      transition: RejectApplication
  - name: StartApplication
    type: operation
    actionMode: sequential
    actions:
      - functionRef:
          refName: startApplicationFunction
          arguments:
            applicant: ".applicant"
    transition: 
      nextState: startApplication2
  - name: startApplication2
    type: operation
    actionMode: sequential
    actions:
      - functionRef:
          refName: startApplicationFunction2
    end: true
  - name: RejectApplication
    type: operation
    actionMode: sequential
    actions:
      - functionRef:
          refName: sendRejectionEmailFunction
          arguments:
            applicant: ".applicant"
    end: true